Iroha rc 1 test ci
soramitsu/iroha2-block-explorer-backend pull request #46
Opened 2024-10-10 20:19 UTC by RamilMus

Added test ci with sarif file upload for github code scanning

2024-10-11 03:56 UTC, 0x009922 requested changes

2024-10-11 03:56 UTC, 0x009922 commented on .github/workflows/rust-clippy.yml
> +      - iroha-rc-1
I would say there is no need to mention this branch here.

```suggestion
```

2024-10-11 03:56 UTC, 0x009922 commented on .github/workflows/rust-clippy.yml
> +name: rust-clippy analyze
```suggestion
name: CI
```

I don't know the best practices on naming though. But it's just a general CI workflow, isn't it.

2024-10-11 03:56 UTC, 0x009922 commented on .github/workflows/rust-clippy.yml
> +  rust-clippy-analyze:
```suggestion
  fmt_clippy_tests:
```

2024-10-11 03:56 UTC, 0x009922 commented on .github/workflows/rust-clippy.yml
> +
I'd also add a step with `cargo fmt -- --check` to check code formatting.

2024-10-11 03:56 UTC, 0x009922 commented on .github/workflows/rust-clippy.yml
> +      run: cargo test --all
```suggestion
      run: cargo test
```

2024-10-11 03:56 UTC, 0x009922 commented on .github/workflows/rust-clippy.yml
It might be beneficial to run all check steps in a single job unconditionally, e.g. even if `cargo clippy` fails, it would be useful to run `cargo test` as well (and `cargo fmt`)

2024-10-14 06:01 UTC, BAStos525 commented on .github/workflows/rust-clippy.yml
Or use `if: always()`

2024-10-14 22:59 UTC, 0x009922 approved these changes

2024-10-15 07:27 UTC, BAStos525 approved these changes

2024-10-15 07:27 UTC, merged